[package]
name = "cli"
edition.workspace = true
repository.workspace = true
version.workspace = true
license.workspace = true
readme.workspace = true
categories.workspace = true

[dependencies]
clap.workspace = true
backup    = { path = "../crates/backup" }
